### ISSUE TITLE
Failed to run `Java: Force Java compilation` with gradle extension

### ISSUE THREAD

**Issue by yuyully** [badsyntax/vscode-gradle#1595]
Extension Name: vscode-gradle
Extension Version: v3.16.4
OS Version: win11
VSCode version: 1.92.2

**Describe the bug**
Failed to run `Java: Force Java compilation` with gradle extension.

**To Reproduce**
1. Clone and open https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/gradle/gradle-11
2. Install redhat.java v1.34.0 (without vscode-gradle extension) > Run `Java: Force Java compilation` > Succeed
3. Continue install vscode-gradle extension > Clean workspace to reload the project > Run `Java: Force Java compilation` > Failed

**Expected behavior**
`Java: Force Java compilation` should be successful with vscode-gradle extension.

**server log**
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-08-29 14:42:54.859
!MESSAGE Failed to build workspace.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Errors occurred during the build.
    at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:612)
    at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:484)
    at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:65)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$28(JDTLanguageServer.java:991)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$61(JDTLanguageServer.java:1226)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Contains: Errors running builder 'Build Server Builder' on project 'gradle-11'.
org.eclipse.core.runtime.CoreException: Build Failed.
    at com.microsoft.gradle.bs.importer.builder.BuildServerBuilder.build(BuildServerBuilder.java:61)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
    at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:595)
    at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:484)
    at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:65)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$28(JDTLanguageServer.java:991)
    at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$61(JDTLanguageServer.java:1226)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Contains: Build Failed.

**Output from "Gradle for Java"**
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.2-bin.zip'.

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by miss-programgamer** [comment]
`"java.configuration.build.tool": "javac"` is not a setting that exists.

**Comment by chagong** [comment]
I validated this again locally, and the issue still exists in the BSP/Tooling API path.

Using the `vscode-java/test/resources/projects/gradle/gradle-11` sample with Gradle 4.10.2, the BSP `GetSourceSetsAction` fails on JDK 21 without extra JVM opens:

```text
java.lang.reflect.InaccessibleObjectException:
Unable to make field private static final java.util.Map
java.lang.ProcessEnvironment.theCaseInsensitiveEnvironment accessible:
module java.base does not "opens java.lang" to unnamed module
```

Root cause: when the Gradle extension is installed, `Java: Force Java compilation` goes through the JDT LS Build Server builder. That delegates to vscode-gradle's BSP server, which runs Gradle through the Tooling API. The Tooling API launcher currently forwards user-provided `java.import.gradle.jvmArguments`, but it does not add the module opens needed by old Gradle/native-platform code when running on modern JDKs. As a result, Gradle 4.10.2 can fail before the build-server model/compile flow completes.

Workaround: configure `java.import.gradle.jvmArguments` with the required module opens and use a JDK new enough to compile the project, for example:

```json
"java.import.gradle.jvmArguments": "--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED"
```

We still need to evaluate if we need to make a production fix for this kind of issue.
